; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=powerpc-unknown-linux-gnu < %s \
; RUN:     -verify-machineinstrs -ppc-asm-full-reg-names \
; RUN:     -ppc-vsr-nums-as-vr -mcpu=broadway | FileCheck %s

define void @dcbz_l_test(i8* %a) {
; CHECK-LABEL: dcbz_l_test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    dcbz_l 0, r3
; CHECK-NEXT:    blr
entry:
  tail call void @llvm.ppc.dcbz.l(i8* %a)
ret void
}

declare void @llvm.ppc.dcbz.l(i8*)